# Generated by Django 2.2.5 on 2020-03-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='HouseRule',
            new_name='house_rule',
        ),
    ]
